/*
 * This source file was generated by the Gradle 'init' task
 */
package homework_pannawat;

public class Car {
    private String brand;
    private String color;
    private int currentSpeed;
    private int maxSpeed;
    private float fuel;
    private float maxFuel;
    private float fuelPerKM;

    public Car(String brand, String color, int maxSpeed, float maxFuel, float fuelPerKM) {
        this.brand = brand;
        this.color = color;
        this.maxSpeed = maxSpeed;
        this.maxFuel = maxFuel;
        this.fuelPerKM = fuelPerKM;
        this.currentSpeed = 0;
        this.fuel = maxFuel;
    }

    public String getColor() {
        return color;
    }

    public String getBrand() {
        return brand;
    }

    public void accelerate() {
        if (currentSpeed < maxSpeed) {
            currentSpeed++;
        }
    }

    public void deaccelerate() {
        if (currentSpeed > 0) {
            currentSpeed--;
        }
    }

    public void drive(float minute) {
        float distance = (currentSpeed / 60.0f) * minute; // กิโลเมตรที่ขับใน 1 นาที

        float fuelNeeded = distance * fuelPerKM;

        if (fuelNeeded <= fuel) {
            fuel -= fuelNeeded;
        } else {
            System.out.println("น้ำมันไม่พอที่จะขับในระยะทางนี้");
        }
    }

    public void addFuel(float fuelAmount) {
        if (fuel + fuelAmount <= maxFuel) {
            fuel += fuelAmount;
        } else {
            fuel = maxFuel; // ถังน้ำมันเต็ม
        }
    }
}
